site_name: faker-news Documentation
site_description: Faker provider for generating fake news content using OpenAI-compatible LLM APIs
site_author: Chris Beaven
site_url: https://github.com/smileychris/faker-news

repo_name: smileychris/faker-news
repo_url: https://github.com/smileychris/faker-news
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started.md
      - Quick Start: quick-start.md
      - Setup & Configuration: setup.md
  - Usage:
      - Library Usage: library-usage.md
      - CLI Reference: cli-reference.md
      - Cache Management: cache-management.md
  - Configuration:
      - Provider Configuration: configuration.md
      - LLM Providers: llm-providers.md
  - Reference:
      - API Reference: api-reference.md
      - Architecture: architecture.md
  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/smileychris/faker-news
