name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v3
        with:
          cache-dependency-path: uv.lock
      - name: Sync dependencies
        run: uv sync --frozen --group dev
      - name: Run tests
        run: uv run pytest -m "not integration and not slow"
